- name: Raspberry Pi 5 setup with Seafile
  hosts: all
  pre_tasks:
    # - name: Log all ansible vars
    #   ansible.builtin.debug:
    #     var: ansible_facts

    - name: Load configuration (with defaults from example file).
      # Load variables from files, dynamically within a task
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_vars_module.html
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.example.yaml
        - config.yaml
      tags:
        - always

    # Allows you to SSH in to the raspberry via SSH, instead of password auth, pulling from your GitHub Public key
    # This allows me to SSH to my raspberry5, mainly from my MacBook Pro laptop
    - name: Ensure SSH Key is authorized (from {{ pi_ssh_authorized_keys }} )
      # Adds or removes an SSH authorized key
      # https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html
      ansible.posix.authorized_key:
        user: pi
        state: present
        key: "{{ pi_ssh_authorized_keys }}"

    # Update system-level dependencies
    - name: Update and upgrade apt packages
      # activate privilege escalation
      become: true # we must use `become` as only root can `apt install`
      # Manages apt-packages
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    - name: Stop running X server
      # Execute commands on targets
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
      ansible.builtin.command: 'update-rc.d lightdm disable'
      become: true
      register: stop_x_output
      changed_when: stop_x_output.rc != 0

  roles:
    - unattended_upgrades
    - docker
    - tailscale
    - docker_seafile
    - backup_seafile
    - auto_reboot
    - useful_bash_aliases

  post_tasks:
    - name: Playbook done notification (via Pushover)
      community.general.pushover:
        msg: 'Ansible done - all ok'
        # pri: -2
        app_token: "{{ pushover_app_token }}"
        user_key: "{{ pushover_user_key }}"
      # This will run on host machine (and not on remote RaspberryPi)
      delegate_to: localhost
